experiments:
  - untreated_vs_stimulated
  - stimulated_vs_US28
  - stimulated_vs_UL33

networks:
  HPRD: "HPRD_Release9_062910_Heinz.txt"
  STRING: "9606.protein.links.v10_mapped_geneIDs_700_no_UBC.txt"
  IREFKEGG: "irefindex14+kegg09.txt_no_UBC.txt"

#ENSEMBL:
#  version: "GRCh38.p10"

FDRs:
  HPRD:
    untreated_vs_stimulated:
      - 0.05 # empty module --> nothing to visualize
    stimulated_vs_US28:
      #- 1e-75
      #- 1e-100
      - 1e-150
      - 1e-175
    stimulated_vs_UL33:
      - 1e-25
      - 1e-50
      - 1e-65
      - 1e-70
  STRING:
    untreated_vs_stimulated:
       - 0.25
    stimulated_vs_US28:
      #- 1e-75
      #- 1e-100
      - 1e-150
      - 1e-175
    stimulated_vs_UL33:
      - 1e-30
      - 1e-50
      - 1e-65
      - 1e-70
  IREFKEGG:
    untreated_vs_stimulated:
      - 0.25
    stimulated_vs_US28:
      - 1e-75
      - 1e-150
    stimulated_vs_UL33:
      - 1e-75

condition_re: "(?P<condition>.+)_[0-9]+"
